import { Snapshot, Profile } from "./identity";
export function identityDemo(admin = false): Snapshot {
  const ola: Profile = {
    id: "demo-ola",
    username: "ola",
    display_name: "Ola (demo)",
    avatar_url: null,
    avatar_path: null,
    role: "Admin",
    requested_role: "Admin",
    access_status: "Approved",
    setup_complete: true,
    is_owner: true,
    created_at: "2026-10-06T08:00:00Z",
  };
  const sam: Profile = {
    ...ola,
    id: "demo-sam",
    username: "samresearch",
    display_name: "Sam (demo)",
    role: "Research Scout",
    requested_role: "Research Scout",
    is_owner: false,
  };
  const john: Profile = {
    ...sam,
    id: "demo-john",
    username: "johnanalyst",
    display_name: "John (demo)",
    role: "Research Scout",
    requested_role: "Analyst",
    access_status: "Pending",
  };
  return {
    profile: admin ? ola : sam,
    profiles: [ola, sam, john],
    email: admin ? "ola@example.com" : "sam@example.com",
    companies: [
      {
        id: "demo-across",
        name: "Across (example)",
        domain: "across.example",
        category: "Cross-chain Protocol",
        status: "Saved",
        created_by: sam.id,
        created_at: "2026-10-06T09:00:00Z",
        merged_into: null,
      },
      {
        id: "demo-nova-1",
        name: "NOVA",
        domain: "nova.example",
        category: "Consumer App",
        status: "Approached",
        created_by: sam.id,
        created_at: "2026-10-06T09:00:00Z",
        merged_into: null,
      },
      {
        id: "demo-nova-2",
        name: "NOVA",
        domain: "novaprotocol.example",
        category: "Protocol",
        status: "Saved",
        created_by: ola.id,
        created_at: "2026-10-06T09:00:00Z",
        merged_into: null,
      },
    ],
    observations: [
      {
        id: "demo-obs-1",
        company_id: "demo-across",
        behaviour: "Bounty",
        description: "Fictional example: a developer bounty announcement.",
        detail: "$20,000",
        observed_on: "2026-10-06",
        submitted_by: sam.id,
        created_at: "2026-10-06T10:00:00Z",
        deleted_at: null,
        merged_into: null,
        duplicate_override: false,
      },
      {
        id: "demo-obs-2",
        company_id: "demo-across",
        behaviour: "KOL Campaign",
        description: "Fictional example: eight creators shared a campaign.",
        detail: "8",
        observed_on: "2026-10-02",
        submitted_by: ola.id,
        created_at: "2026-10-02T10:00:00Z",
        deleted_at: null,
        merged_into: null,
        duplicate_override: false,
      },
      {
        id: "demo-obs-3",
        company_id: "demo-nova-1",
        behaviour: "Fundraise",
        description: "Fictional example: a funding announcement.",
        detail: "$8M",
        observed_on: "2026-10-05",
        submitted_by: sam.id,
        created_at: "2026-10-05T10:00:00Z",
        deleted_at: null,
        merged_into: null,
        duplicate_override: false,
      },
    ],
    sources: [
      {
        id: "demo-source-1",
        observation_id: "demo-obs-1",
        url: "https://news.example/bounty",
        normalized_url: "https://news.example/bounty",
        submitted_by: sam.id,
        created_at: "2026-10-06T10:00:00Z",
        deleted_at: null,
      },
      {
        id: "demo-source-2",
        observation_id: "demo-obs-1",
        url: "https://superteam.example/bounty",
        normalized_url: "https://superteam.example/bounty",
        submitted_by: ola.id,
        created_at: "2026-10-06T11:00:00Z",
        deleted_at: null,
      },
    ],
    activity: [
      {
        id: "demo-log",
        actor_id: sam.id,
        event: "Observation submitted",
        entity_id: "demo-obs-1",
        details: {},
        created_at: "2026-10-06T10:00:00Z",
      },
    ],
  };
}
